.deploy_task: &deploy_task
  stage: deploy
  script:
    - sudo chef-client --runlist 'recipe[gyc_wifi_server::app_login]' --config /home/deploy/client.rb

staging:
  <<: *deploy_task
  environment: staging
  tags:
    - staging
  only:
    - develop

demo:
  <<: *deploy_task
  environment: demo
  tags:
    - demo
  only:
    - demo

vagrant:
  <<: *deploy_task
  environment: vagrant
  tags:
    - vagrant
  only:
    - vagrant

production:
  <<: *deploy_task
  environment: production
  tags:
    - production
  only:
    - production
