.deploy_task: &deploy_task
  stage: deploy
  script:
    - sudo chef-client --local-mode --runlist 'recipe[gyc_wifi_server::app_login]' --logfile /var/log/chef-client --json-attributes /home/deploy/chef_config.json

staging:
  <<: *deploy_task
  environment: staging
  tags:
    - staging
  only:
    - develop
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^release.*$/

production:
  <<: *deploy_task
  environment: production
  tags:
    - production
  only:
    - master
    - tags
  except:
    - develop
    - /^feature.*$/
    - /^bugfix.*$/
    - /^hotfix.*$/
    - /^release.*$/
